name: Release MoyuShuang

on:
  push:
    tags:
      - 'v*' # 当推送 v1.0.0, v0.1.2 等标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义需要交叉编译的目标平台
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          BINARY_NAME=moyu-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="$BINARY_NAME.exe"
          fi
          go build -o "$BINARY_NAME" main.go
          echo "BINARY_PATH=$BINARY_NAME" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BINARY_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}